### ISSUE TITLE
CNAME

### ISSUE THREAD

**Issue by emiben027** [goldilocks5/bypork#44]
CNAME is an important file and as such shouldn't be deleted. It's the reason why bypork is live.

**Comment by goldilocks5** [comment]
Oh! I'm sorry, I should have explained why I had to take that action
earlier.

We have been having some complications with integrating the backend.

Ayo thought I should disabled the GitHub page for now so that it is hosted
directly from the Cpanel.

**Comment by emiben027** [comment]
Alright
